import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 bg-yellow-300 shadow">
          <form action="/items" method="GET" className="flex gap-2">
            <input
              type="text"
              name="search" 
              placeholder="Buscar..."
              className="px-3 py-2 rounded bg-white text-black w-100"
            />
            <button
              type="submit"
              className="px-4 py-2 ml-4 bg-gray-200 text-black rounded hover:bg-gray-300"
            >
              Buscar
            </button>
          </form>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
